### ISSUE TITLE
Cannot link Google At AuthCore Settings after I tried to login with an un-registered Google account

### ISSUE THREAD

**Issue by rickmak** [likecoin/like-co#1454]
I already have a linker ID: rickmak

The above linker ID is connected with Twitter, Apple and Matters.

I cannot connect to Google at https://like.co/in/settings -> AuthCore Setting -> Setting now. After the following happen this morning:

1. I login in a new computer, I press login with Google without much though.
1. After I click login with Google, it go through the  signup process. I realized my Liker ID is not linked with Google ID.
1. I close the tab.
1. Open the liker.land again and Login using Apple ID.
1. After successful login, I tried to connect with Google at the setting page.
1. An error, `The contact has been used in the system so cannot link with this social platform` is displayed.

## Expected

An uncompleted signup for me should not consume the Google ID to a phantom account.

**Comment by williamchong007** [comment]
Sorry for the inconvenience caused, this is a know issue due to [authcore](https://authcore.io/) being an independent account system not completely controlled by like.co.

Could you please contact support via the chat bubble in the bottom right corner in https://like.co/in ? We can help you with the google linking issue there.

**Comment by rickmak** [comment]
Thanks @williamchong007 I take is as `don't fix`. cc AuthCore dev @kcchu
